### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Alexbalala** [cambrian-mllm/cambrian#43]
when i run model_worker.py to deployment cambrian 34b, sometimes i always meets this error.
``Loading checkpoint shards: 100%|██████████| 32/32 [00:55<00:00,  1.75s/it]
Traceback (most recent call last):
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/mnt/disk2/xuyawen/anaconda3/envs/cambrian/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by Anuska12** [comment]
Hello!

Did you solve it?
