### ISSUE TITLE
Cannot run inference with Cambrian-1-34B on multi-GPU

### ISSUE THREAD

**Issue by Lopa07** [cambrian-mllm/cambrian#58]
- I am trying to run inference with Cambrian-1-34B.
- I have RTX 6000 GPUs with 48GBs.
- I following [this inference script](https://github.com/cambrian-mllm/cambrian/blob/main/inference.py).

The Cambrian-1-34B requires multiple GPUs to run. But it is throwing the following error:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method
in method wrapper_CUDA__native_layer_norm)
```
I tried following the changes suggested in [this issue](https://github.com/cambrian-mllm/cambrian/issues/12). That also did not work.

**Comment by Lopa07** [comment]
The whole stack:
```
2024-07-20 16:49:05 PID=2363969 __init__.py:49 setup_logging() INFO → 'standard' logger initialized.                                                        
2024-07-20 16:49:06 PID=2363969 builder.py:119 load_pretrained_model() INFO → Loading Cambrian from cambrian-34b                                            
2024-07-20 16:49:06 PID=2363969 builder.py:105 build_vision_tower_aux_list() INFO → Loading **SigLIP CLIP** Vision Tower: siglip/CLIP-ViT-SO400M-14-384-inte
rp576                                                                                                                                                       
2024-07-20 16:49:06 PID=2363969 base_encoder.py:44 __init__() WARNING → Unfreezing MM Vision Tower: False                                                   
2024-07-20 16:49:06 PID=2363969 builder.py:99 build_vision_tower_aux_list() INFO → Loading **OpenAI CLIP** Vision Tower: openai/clip-vit-large-patch14-336-i
nterp576                                                                                                                                                    
2024-07-20 16:49:06 PID=2363969 base_encoder.py:44 __init__() WARNING → Unfreezing MM Vision Tower: False                                                   
/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is depr
ecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.         
  warnings.warn(                                                                                                                                            
2024-07-20 16:49:07 PID=2363969 builder.py:116 build_vision_tower_aux_list() INFO → Loading **DINO Vision Tower: facebook/dinov2-giant-res378-interp576     
2024-07-20 16:49:07 PID=2363969 base_encoder.py:44 __init__() WARNING → Unfreezing MM Vision Tower: False                                                   
2024-07-20 16:49:07 PID=2363969 builder.py:111 build_vision_tower_aux_list() INFO → Loading **ConvNeXt CLIP** Vision Tower: clip-convnext-XXL-multi-stage-in
terp9216                                                                                                                                                    
2024-07-20 16:49:07 PID=2363969 base_encoder.py:44 __init__() WARNING → Unfreezing MM Vision Tower: False                                                   
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:24<00:00,  1.32it/s]      
2024-07-20 16:49:34 PID=2363969 factory.py:227 create_model() INFO → Loaded hf-hub:timm/ViT-SO400M-14-SigLIP-384 model config.                              
2024-07-20 16:49:41 PID=2363969 factory.py:314 create_model() INFO → Loading pretrained hf-hub:timm/ViT-SO400M-14-SigLIP-384 weights (/home/m.banerjee/.cach
e/huggingface/hub/models--timm--ViT-SO400M-14-SigLIP-384/snapshots/ac16108d567c4389e6cd2b11c9b8585f7474435b/open_clip_pytorch_model.bin).                   
2024-07-20 16:49:45 PID=2363969 dino_encoder.py:89 load_model() WARNING → Overriding DinoVisionTower image size of 518 with 378                             
2024-07-20 16:49:45 PID=2363969 dino_encoder.py:98 load_model() INFO → Dino Vision Processor: BitImageProcessor {                                           
  "crop_size": {                                                                                                                                            
    "height": 378,                                                                                                                                          
    "width": 378                                                                                                                                            
  },                                                                                                                                                        
  "do_center_crop": true,                                                                                                                                   
  "do_convert_rgb": true,                                                                                                                                   
  "do_normalize": true,                                                                                                                                     
  "do_rescale": true,                                                                                                                                       
  "do_resize": true,                                                                                                                                        
  "image_mean": [                                                                                                                                           
    0.485,                                                                                                                                                  
    0.456,                                                                                                                                                  
    0.406                                                                                                                                                   
  ],                                                                                                                                                        
  "image_processor_type": "BitImageProcessor",                                                                                                              
  "image_std": [                                                                                                                                            
    0.229,                                                                                                                                                  
    0.224,                                                                                                                                                  
    0.225                                                                                                                                                   
  ],                                                                                                                                                        
  "resample": 3,                                                                                                                                            
  "rescale_factor": 0.00392156862745098,                                                                                                                    
  "size": {                            
    "shortest_edge": 378               
  }                                    
}                                      

2024-07-20 16:49:46 PID=2363969 factory.py:227 create_model() INFO → Loaded hf-hub:laion/CLIP-convnext_xxlarge-laion2B-s34B-b82K-augreg-soup model config.
2024-07-20 16:49:55 PID=2363969 factory.py:314 create_model() INFO → Loading pretrained hf-hub:laion/CLIP-convnext_xxlarge-laion2B-s34B-b82K-augreg-soup wei
ghts (/home/m.banerjee/.cache/huggingface/hub/models--laion--CLIP-convnext_xxlarge-laion2B-s34B-b82K-augreg-soup/snapshots/9f3e8ee3f383c672388d9178afe70af9e
63ac9df/open_clip_pytorch_model.bin).
Traceback (most recent call last):                                                                                                                          
  File "/VDIL_COREML/m.banerjee/actionable_ai_tv/alignment/run_prompts_w_cambrian.py", line 90, in <module>                                                 
    output_ids = model.generate(                                                                                                                            
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context             
    return func(*args, **kwargs)                                                                                                                            
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/cambrian/model/language_model/cambrian_llama.py", line 462, in generate
    ) = self.prepare_inputs_labels_for_multimodal(                                                                                                          
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/cambrian/model/cambrian_arch.py", line 366, in prepare_inputs_labels_fo
r_multimodal
    image_aux_features_list = self.encode_images(image_aux_list)              
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/cambrian/model/cambrian_arch.py", line 336, in encode_images           
    image_aux_features = vision_tower_aux(image_aux)                          
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl          
    return self._call_impl(*args, **kwargs)                                   
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                  
    return forward_call(*args, **kwargs)                                      
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/cambrian/model/multimodal_encoder/base_encoder.py", line 62, in forward
    image_features = self._forward(images)                                    
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/cambrian/model/multimodal_encoder/clip_encoder.py", line 104, in _forwa
rd
    image_forward_outs = self.vision_tower(images.to(device=self.device, dtype=self.dtype), output_hidden_states=True)                                      
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl          
    return self._call_impl(*args, **kwargs)                                   
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                  
    return forward_call(*args, **kwargs)                                      
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward                         
    output = old_forward(*args, **kwargs)                                     
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 917, in forward       
    return self.vision_model(          
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl          
    return self._call_impl(*args, **kwargs)                                   
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                  
    return forward_call(*args, **kwargs)                                      
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 844, in forward       
    encoder_outputs = self.encoder(    
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl          
    return self._call_impl(*args, **kwargs)                                   
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                  
    return forward_call(*args, **kwargs)                                      
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 630, in forward       
    layer_outputs = encoder_layer(     
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl          
    return self._call_impl(*args, **kwargs)                                   
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                  
    return forward_call(*args, **kwargs)                                      
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward                         
    output = old_forward(*args, **kwargs)                                     
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 371, in forward       
    hidden_states = self.layer_norm1(hidden_states)                           
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl          
    return self._call_impl(*args, **kwargs)                                   
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                  
    return forward_call(*args, **kwargs)                                      
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward                         
    output = old_forward(*args, **kwargs)                                     
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 201, in forward               
    return F.layer_norm(               
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/cambrian/lib/python3.10/site-packages/torch/nn/functional.py", line 2546, in layer_norm                      
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)                                                       
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight 
in method wrapper_CUDA__native_layer_norm)
```

**Comment by LanceLeonhart** [comment]
Also run into this problem! But I cannot solve this problem yet. The only way I find is to use "CUDA_VISIBLE_DEVICES=" instruction  to set all the tensors on the same GPU. However, when running large experiments, I run into CUDA OutOfMemory Error and cannot solve it. I'm also using RTX 6000. Hope that somebody can help with this issue.

**Comment by FSet89** [comment]
Any update on this?

**Comment by lyiqian** [comment]
You might want to try
```
load_pretrained_model(
    ...
    load_8bit=True  # or even load_4bit=True
)
```

Managed to run the 3b model @ 4bit on 1080Ti.
